[repository]
name = "device-windowrule"
authors = "Virt"
commit_pins = [
    # v Hyprland                                  v hypr-device-windowrule
    ["9958d297641b5c84dcff93f9039d80a5ad37ab00", "9947768a2afcd29d089b5b758e3e4dc948a27465"], # v0.49.0
    ["c4a4c341568944bd4fb9cd503558b2de602c0213", "9947768a2afcd29d089b5b758e3e4dc948a27465"], # v0.50.0
    ["4e242d086e20b32951fdc0ebcbfb4d41b5be8dcc", "9947768a2afcd29d089b5b758e3e4dc948a27465"], # v0.50.1
    ["46174f78b374b6cea669c48880877a8bdcf7802f", "68f539a431175dd5970156b356b94505d88978b8"], # v0.51.0
    ["71a1216abcc7031776630a6d88f105605c4dc1c9", "68f539a431175dd5970156b356b94505d88978b8"], # v0.51.1
    ["f56ec180d3a03a5aa978391249ff8f40f949fb73", "19294ebd29965a702b5ebdfd230ea9bb7456f995"], # v0.52.0
    ["967c3c7404d4fa00234e29c70df3e263386d2597", "19294ebd29965a702b5ebdfd230ea9bb7456f995"], # v0.52.1
    ["386376400119dd46a767c9f8c8791fd22c7b6e61", "19294ebd29965a702b5ebdfd230ea9bb7456f995"], # v0.52.2
    ["ea444c35bb23b6e34505ab6753e069de7801cc25", "6ab227ca59b5449d2d3e90363a4721306c030904"], # v0.53.0
    ["ab1d80f3d6aebd57a0971b53a1993b1c1dfe0b09", "6ab227ca59b5449d2d3e90363a4721306c030904"], # v0.53.1
    ["39f3feddbee4a66be9608ed1eb7e73878d596b50", "6ab227ca59b5449d2d3e90363a4721306c030904"], # v0.53.2
    ["dd220efe7b1e292415bd0ea7161f63df9c95bfd3", "6ab227ca59b5449d2d3e90363a4721306c030904"], # v0.53.3
]

[dynamic-cursors]
description = "apply input device config based on the focused window"
authors = ["Virt"]
output = "out/device-windowrule.so"
build = [
    "make all",
]
